on:
  release:
    types:
      - published

jobs:
  prerelease:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease && !github.event.release.draft
    steps:
      - run: echo "Prerelease"
